# Generated by Django 3.2 on 2021-07-01 06:43

import app_users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_auto_20210523_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCAProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('des', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cca_pic', models.ImageField(blank=True, upload_to=app_users.models.path_and_rename, verbose_name='poster')),
            ],
        ),
    ]
