# Generated by Django 3.2 on 2021-07-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_ccaprofileinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccaprofileinfo',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
